/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CombImagenes;

/**
 *
 * @author Ale
 */
public class CombImag extends javax.swing.JFrame {

    /**
     * Creates new form CombImag
     */
    public CombImag() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imag = new javax.swing.JLabel();
        chkBarbilla = new javax.swing.JCheckBox();
        chkLentes = new javax.swing.JCheckBox();
        chkCabello = new javax.swing.JCheckBox();
        chkDientes = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/geek-----.gif"))); // NOI18N

        chkBarbilla.setText("Barbilla");
        chkBarbilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBarbillaActionPerformed(evt);
            }
        });

        chkLentes.setText("Lentes");
        chkLentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLentesActionPerformed(evt);
            }
        });

        chkCabello.setText("Cabello");
        chkCabello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCabelloActionPerformed(evt);
            }
        });

        chkDientes.setText("Dientes");
        chkDientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDientesActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Combinacion de Imagenes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkDientes)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkBarbilla)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkLentes)
                            .addComponent(chkCabello))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addComponent(imag)
                        .addGap(56, 56, 56))))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(chkBarbilla)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(chkLentes)
                        .addGap(18, 18, 18)
                        .addComponent(chkCabello))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(imag)))
                .addGap(21, 21, 21)
                .addComponent(chkDientes)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkBarbillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBarbillaActionPerformed
        // TODO add your handling code here:
        imag.setIcon(new javax.swing.ImageIcon(getClass().getResource(String.format("/Imagenes/%s", calcularNom()))));
  
    }//GEN-LAST:event_chkBarbillaActionPerformed

    private void chkLentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLentesActionPerformed
        // TODO add your handling code here:
        imag.setIcon(new javax.swing.ImageIcon(getClass().getResource(String.format("/Imagenes/%s", calcularNom()))));
    }//GEN-LAST:event_chkLentesActionPerformed

    private void chkCabelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCabelloActionPerformed
        // TODO add your handling code here:
        imag.setIcon(new javax.swing.ImageIcon(getClass().getResource(String.format("/Imagenes/%s", calcularNom()))));
    }//GEN-LAST:event_chkCabelloActionPerformed

    private void chkDientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDientesActionPerformed
        // TODO add your handling code here:
        imag.setIcon(new javax.swing.ImageIcon(getClass().getResource(String.format("/Imagenes/%s", calcularNom()))));
    }//GEN-LAST:event_chkDientesActionPerformed
    
    private String calcularNom(){
       String resultado = "geek-";
       
       resultado = resultado + (chkBarbilla.isSelected() ? "c" : "-");
       resultado = resultado + (chkLentes.isSelected() ? "g" : "-");
       resultado = resultado + (chkCabello.isSelected() ? "h" : "-");
       resultado = resultado + (chkDientes.isSelected() ? "t" : "-");
       
      
       
       return resultado + ".gif";
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CombImag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CombImag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CombImag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CombImag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CombImag().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkBarbilla;
    private javax.swing.JCheckBox chkCabello;
    private javax.swing.JCheckBox chkDientes;
    private javax.swing.JCheckBox chkLentes;
    private javax.swing.JLabel imag;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
